export const data = JSON.parse("{\"key\":\"v-5ce9de6d\",\"path\":\"/dev-tutorial/20220729-cdn.html\",\"title\":\"网站访问太慢，不妨试试这些 CDN\",\"lang\":\"zh-CN\",\"frontmatter\":{\"title\":\"网站访问太慢，不妨试试这些 CDN\",\"sidebar_position\":1,\"description\":\"相关信息 不要哀求，学会争取。若是如此，终有所获。 提示 原文：https://mp.weixin.qq.com/s/WDOc5kI0jVtsbxgWwCoJkQ\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://cunyu1943.github.io/dev-tutorial/20220729-cdn.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"JavaPark\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"网站访问太慢，不妨试试这些 CDN\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"相关信息 不要哀求，学会争取。若是如此，终有所获。 提示 原文：https://mp.weixin.qq.com/s/WDOc5kI0jVtsbxgWwCoJkQ\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"村雨遥\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"网站访问太慢，不妨试试这些 CDN\\\",\\\"image\\\":[\\\"\\\"],\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"村雨遥\\\",\\\"url\\\":\\\"https://cunyu1943.github.io\\\",\\\"email\\\":\\\"747731461@qq.com\\\"}]}\"]]},\"headers\":[{\"level\":2,\"title\":\"前言\",\"slug\":\"前言\",\"link\":\"#前言\",\"children\":[]},{\"level\":2,\"title\":\"cdnjs.com\",\"slug\":\"cdnjs-com\",\"link\":\"#cdnjs-com\",\"children\":[]},{\"level\":2,\"title\":\"字节跳动\",\"slug\":\"字节跳动\",\"link\":\"#字节跳动\",\"children\":[]},{\"level\":2,\"title\":\"jsDelivr\",\"slug\":\"jsdelivr\",\"link\":\"#jsdelivr\",\"children\":[]},{\"level\":2,\"title\":\"UNPKG\",\"slug\":\"unpkg\",\"link\":\"#unpkg\",\"children\":[]},{\"level\":2,\"title\":\"BootCDN\",\"slug\":\"bootcdn\",\"link\":\"#bootcdn\",\"children\":[]},{\"level\":2,\"title\":\"75 CDN\",\"slug\":\"_75-cdn\",\"link\":\"#_75-cdn\",\"children\":[]},{\"level\":2,\"title\":\"Staticfile CDN\",\"slug\":\"staticfile-cdn\",\"link\":\"#staticfile-cdn\",\"children\":[]},{\"level\":2,\"title\":\"总结\",\"slug\":\"总结\",\"link\":\"#总结\",\"children\":[]}],\"readingTime\":{\"minutes\":3.57,\"words\":1070},\"filePathRelative\":\"dev-tutorial/20220729-cdn.md\",\"excerpt\":\"<div class=\\\"hint-container info\\\">\\n<p class=\\\"hint-container-title\\\">相关信息</p>\\n<p>不要哀求，学会争取。若是如此，终有所获。</p>\\n</div>\\n<div class=\\\"hint-container tip\\\">\\n<p class=\\\"hint-container-title\\\">提示</p>\\n<p>原文：<a href=\\\"https://mp.weixin.qq.com/s/WDOc5kI0jVtsbxgWwCoJkQ\\\" target=\\\"_blank\\\" rel=\\\"noopener noreferrer\\\">https://mp.weixin.qq.com/s/WDOc5kI0jVtsbxgWwCoJkQ</a></p>\\n</div>\",\"copyright\":{\"author\":\"村雨遥\",\"license\":\"著作权归作者所有。商业转载请联系作者获得授权，非商业转载请注明出处\"},\"autoDesc\":true}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
