export const data = JSON.parse("{\"key\":\"v-00907cee\",\"path\":\"/dev-tutorial/20221127-cmd.html\",\"title\":\"黑客大神也常用的一些 CMD 命令\",\"lang\":\"zh-CN\",\"frontmatter\":{\"title\":\"黑客大神也常用的一些 CMD 命令\",\"sidebar_position\":3,\"description\":\"相关信息 不要哀求，学会争取。若是如此，终有所获。 提示 原文：https://mp.weixin.qq.com/s/LAZY7sMiwzNwimTpmlh0rw\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://cunyu1943.github.io/dev-tutorial/20221127-cmd.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"JavaPark\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"黑客大神也常用的一些 CMD 命令\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"相关信息 不要哀求，学会争取。若是如此，终有所获。 提示 原文：https://mp.weixin.qq.com/s/LAZY7sMiwzNwimTpmlh0rw\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"村雨遥\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"黑客大神也常用的一些 CMD 命令\\\",\\\"image\\\":[\\\"\\\"],\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"村雨遥\\\",\\\"url\\\":\\\"https://cunyu1943.github.io\\\",\\\"email\\\":\\\"747731461@qq.com\\\"}]}\"]]},\"headers\":[{\"level\":2,\"title\":\"前言\",\"slug\":\"前言\",\"link\":\"#前言\",\"children\":[]},{\"level\":2,\"title\":\"如何打开命令提示符窗口\",\"slug\":\"如何打开命令提示符窗口\",\"link\":\"#如何打开命令提示符窗口\",\"children\":[]},{\"level\":2,\"title\":\"常用命令\",\"slug\":\"常用命令\",\"link\":\"#常用命令\",\"children\":[{\"level\":3,\"title\":\"目录操作\",\"slug\":\"目录操作\",\"link\":\"#目录操作\",\"children\":[]},{\"level\":3,\"title\":\"开关机操作\",\"slug\":\"开关机操作\",\"link\":\"#开关机操作\",\"children\":[]},{\"level\":3,\"title\":\"网络操作\",\"slug\":\"网络操作\",\"link\":\"#网络操作\",\"children\":[]},{\"level\":3,\"title\":\"进程/服务操作\",\"slug\":\"进程-服务操作\",\"link\":\"#进程-服务操作\",\"children\":[]},{\"level\":3,\"title\":\"其他操作\",\"slug\":\"其他操作\",\"link\":\"#其他操作\",\"children\":[]}]},{\"level\":2,\"title\":\"总结\",\"slug\":\"总结\",\"link\":\"#总结\",\"children\":[]}],\"readingTime\":{\"minutes\":2.67,\"words\":800},\"filePathRelative\":\"dev-tutorial/20221127-cmd.md\",\"excerpt\":\"<div class=\\\"hint-container info\\\">\\n<p class=\\\"hint-container-title\\\">相关信息</p>\\n<p>不要哀求，学会争取。若是如此，终有所获。</p>\\n</div>\\n<div class=\\\"hint-container tip\\\">\\n<p class=\\\"hint-container-title\\\">提示</p>\\n<p>原文：<a href=\\\"https://mp.weixin.qq.com/s/LAZY7sMiwzNwimTpmlh0rw\\\" target=\\\"_blank\\\" rel=\\\"noopener noreferrer\\\">https://mp.weixin.qq.com/s/LAZY7sMiwzNwimTpmlh0rw</a></p>\\n</div>\",\"copyright\":{\"author\":\"村雨遥\",\"license\":\"著作权归作者所有。商业转载请联系作者获得授权，非商业转载请注明出处\"},\"autoDesc\":true}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
