export const data = JSON.parse("{\"key\":\"v-75ca8fc5\",\"path\":\"/2023/0527-0602.html\",\"title\":\"好物周刊#7：浏览器标签页也可以这么酷\",\"lang\":\"zh-CN\",\"frontmatter\":{\"description\":\"好物周刊#7：浏览器标签页也可以这么酷 不要哀求，学会争取。若是如此，终有所获。 原文：https://mp.weixin.qq.com/s/s3NpyL6JeybdJfHurlOakw 🎈 项目 Qexo\"},\"headers\":[{\"level\":2,\"title\":\"🎈 项目\",\"slug\":\"🎈-项目\",\"link\":\"#🎈-项目\",\"children\":[{\"level\":3,\"title\":\"Qexo\",\"slug\":\"qexo\",\"link\":\"#qexo\",\"children\":[]},{\"level\":3,\"title\":\"Twikoo\",\"slug\":\"twikoo\",\"link\":\"#twikoo\",\"children\":[]},{\"level\":3,\"title\":\"ILLA Builder\",\"slug\":\"illa-builder\",\"link\":\"#illa-builder\",\"children\":[]}]},{\"level\":2,\"title\":\"💻 软件\",\"slug\":\"💻-软件\",\"link\":\"#💻-软件\",\"children\":[{\"level\":3,\"title\":\"IINA\",\"slug\":\"iina\",\"link\":\"#iina\",\"children\":[]},{\"level\":3,\"title\":\"PP 鸭\",\"slug\":\"pp-鸭\",\"link\":\"#pp-鸭\",\"children\":[]},{\"level\":3,\"title\":\"PhotoBulk\",\"slug\":\"photobulk\",\"link\":\"#photobulk\",\"children\":[]}]},{\"level\":2,\"title\":\"🕸️ 网站\",\"slug\":\"🕸️-网站\",\"link\":\"#🕸️-网站\",\"children\":[{\"level\":3,\"title\":\"简视频\",\"slug\":\"简视频\",\"link\":\"#简视频\",\"children\":[]},{\"level\":3,\"title\":\"Star Charts\",\"slug\":\"star-charts\",\"link\":\"#star-charts\",\"children\":[]},{\"level\":3,\"title\":\"Simple Icons\",\"slug\":\"simple-icons\",\"link\":\"#simple-icons\",\"children\":[]}]},{\"level\":2,\"title\":\"🔌 插件\",\"slug\":\"🔌-插件\",\"link\":\"#🔌-插件\",\"children\":[{\"level\":3,\"title\":\"Washbaidu\",\"slug\":\"washbaidu\",\"link\":\"#washbaidu\",\"children\":[]},{\"level\":3,\"title\":\"青柠起始页\",\"slug\":\"青柠起始页\",\"link\":\"#青柠起始页\",\"children\":[]},{\"level\":3,\"title\":\"iTab\",\"slug\":\"itab\",\"link\":\"#itab\",\"children\":[]}]},{\"level\":2,\"title\":\"📖 资料\",\"slug\":\"📖-资料\",\"link\":\"#📖-资料\",\"children\":[{\"level\":3,\"title\":\"OI Wiki\",\"slug\":\"oi-wiki\",\"link\":\"#oi-wiki\",\"children\":[]},{\"level\":3,\"title\":\"CTF Wiki\",\"slug\":\"ctf-wiki\",\"link\":\"#ctf-wiki\",\"children\":[]},{\"level\":3,\"title\":\"菜鸟教程\",\"slug\":\"菜鸟教程\",\"link\":\"#菜鸟教程\",\"children\":[]}]},{\"level\":2,\"title\":\"✍️ 说明\",\"slug\":\"✍️-说明\",\"link\":\"#✍️-说明\",\"children\":[]},{\"level\":2,\"title\":\"🎬️ 广告\",\"slug\":\"🎬️-广告\",\"link\":\"#🎬️-广告\",\"children\":[]}],\"readingTime\":{\"minutes\":6.11,\"words\":1834},\"filePathRelative\":\"2023/0527-0602.md\",\"excerpt\":\"<h1> 好物周刊#7：浏览器标签页也可以这么酷</h1>\\n<blockquote>\\n<p>不要哀求，学会争取。若是如此，终有所获。</p>\\n<p>原文：<a href=\\\"https://mp.weixin.qq.com/s/s3NpyL6JeybdJfHurlOakw\\\" target=\\\"_blank\\\" rel=\\\"noopener noreferrer\\\">https://mp.weixin.qq.com/s/s3NpyL6JeybdJfHurlOakw</a></p>\\n</blockquote>\\n<h2> 🎈 项目</h2>\\n<h3> <a href=\\\"https://github.com/Qexo/Qexo\\\" target=\\\"_blank\\\" rel=\\\"noopener noreferrer\\\">Qexo</a></h3>\",\"copyright\":{\"author\":\"村雨遥\",\"license\":\"著作权归作者所有。商业转载请联系作者获得授权，非商业转载请注明出处\"},\"autoDesc\":true}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
