export const data = JSON.parse("{\"key\":\"v-f3d6a946\",\"path\":\"/2023/0610-0616.html\",\"title\":\"好物周刊#9：AI 学习必备资料\",\"lang\":\"zh-CN\",\"frontmatter\":{\"description\":\"好物周刊#9：AI 学习必备资料 不要哀求，学会争取。若是如此，终有所获。 原文：https://mp.weixin.qq.com/s/qgnhS4UUnWWuKonROqMA7g 🎈 项目 PicX\"},\"headers\":[{\"level\":2,\"title\":\"🎈 项目\",\"slug\":\"🎈-项目\",\"link\":\"#🎈-项目\",\"children\":[{\"level\":3,\"title\":\"PicX\",\"slug\":\"picx\",\"link\":\"#picx\",\"children\":[]},{\"level\":3,\"title\":\"Cloudreve\",\"slug\":\"cloudreve\",\"link\":\"#cloudreve\",\"children\":[]},{\"level\":3,\"title\":\"pinyin-pro\",\"slug\":\"pinyin-pro\",\"link\":\"#pinyin-pro\",\"children\":[]}]},{\"level\":2,\"title\":\"💻 软件\",\"slug\":\"💻-软件\",\"link\":\"#💻-软件\",\"children\":[{\"level\":3,\"title\":\"PDDON\",\"slug\":\"pddon\",\"link\":\"#pddon\",\"children\":[]},{\"level\":3,\"title\":\"Kap\",\"slug\":\"kap\",\"link\":\"#kap\",\"children\":[]},{\"level\":3,\"title\":\"班迪录屏\",\"slug\":\"班迪录屏\",\"link\":\"#班迪录屏\",\"children\":[]}]},{\"level\":2,\"title\":\"🕸️ 网站\",\"slug\":\"🕸️-网站\",\"link\":\"#🕸️-网站\",\"children\":[{\"level\":3,\"title\":\"TXT 文本处理工具\",\"slug\":\"txt-文本处理工具\",\"link\":\"#txt-文本处理工具\",\"children\":[]},{\"level\":3,\"title\":\"Text-Image\",\"slug\":\"text-image\",\"link\":\"#text-image\",\"children\":[]},{\"level\":3,\"title\":\"一个工具箱\",\"slug\":\"一个工具箱\",\"link\":\"#一个工具箱\",\"children\":[]}]},{\"level\":2,\"title\":\"🔌 插件\",\"slug\":\"🔌-插件\",\"link\":\"#🔌-插件\",\"children\":[{\"level\":3,\"title\":\"Grammarly\",\"slug\":\"grammarly\",\"link\":\"#grammarly\",\"children\":[]},{\"level\":3,\"title\":\"Smart TOC\",\"slug\":\"smart-toc\",\"link\":\"#smart-toc\",\"children\":[]},{\"level\":3,\"title\":\"FeHelper\",\"slug\":\"fehelper\",\"link\":\"#fehelper\",\"children\":[]}]},{\"level\":2,\"title\":\"📖 资料\",\"slug\":\"📖-资料\",\"link\":\"#📖-资料\",\"children\":[{\"level\":3,\"title\":\"机器学习 100 天\",\"slug\":\"机器学习-100-天\",\"link\":\"#机器学习-100-天\",\"children\":[]},{\"level\":3,\"title\":\"强化学习 100 题\",\"slug\":\"强化学习-100-题\",\"link\":\"#强化学习-100-题\",\"children\":[]},{\"level\":3,\"title\":\"深度学习 500 问\",\"slug\":\"深度学习-500-问\",\"link\":\"#深度学习-500-问\",\"children\":[]}]},{\"level\":2,\"title\":\"✍️ 说明\",\"slug\":\"✍️-说明\",\"link\":\"#✍️-说明\",\"children\":[]},{\"level\":2,\"title\":\"🎬️ 广告\",\"slug\":\"🎬️-广告\",\"link\":\"#🎬️-广告\",\"children\":[]}],\"readingTime\":{\"minutes\":5.99,\"words\":1797},\"filePathRelative\":\"2023/0610-0616.md\",\"excerpt\":\"<h1> 好物周刊#9：AI 学习必备资料</h1>\\n<blockquote>\\n<p>不要哀求，学会争取。若是如此，终有所获。</p>\\n<p>原文：<a href=\\\"https://mp.weixin.qq.com/s/qgnhS4UUnWWuKonROqMA7g\\\" target=\\\"_blank\\\" rel=\\\"noopener noreferrer\\\">https://mp.weixin.qq.com/s/qgnhS4UUnWWuKonROqMA7g</a></p>\\n</blockquote>\\n<h2> 🎈 项目</h2>\\n<h3> <a href=\\\"https://github.com/XPoet/picx\\\" target=\\\"_blank\\\" rel=\\\"noopener noreferrer\\\">PicX</a></h3>\",\"copyright\":{\"author\":\"村雨遥\",\"license\":\"著作权归作者所有。商业转载请联系作者获得授权，非商业转载请注明出处\"},\"autoDesc\":true}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
