export const data = JSON.parse("{\"key\":\"v-40e87e88\",\"path\":\"/2023/0624-0630.html\",\"title\":\"好物周刊#11：远程桌面软件对对碰\",\"lang\":\"zh-CN\",\"frontmatter\":{\"description\":\"好物周刊#11：远程桌面软件对对碰 不要哀求，学会争取。若是如此，终有所获。 原文：https://mp.weixin.qq.com/s/4az9STvM2jiwHhRa_k060Q 🎈 项目 live\"},\"headers\":[{\"level\":2,\"title\":\"🎈 项目\",\"slug\":\"🎈-项目\",\"link\":\"#🎈-项目\",\"children\":[{\"level\":3,\"title\":\"live\",\"slug\":\"live\",\"link\":\"#live\",\"children\":[]},{\"level\":3,\"title\":\"蓝鲸直播源\",\"slug\":\"蓝鲸直播源\",\"link\":\"#蓝鲸直播源\",\"children\":[]},{\"level\":3,\"title\":\"wtv\",\"slug\":\"wtv\",\"link\":\"#wtv\",\"children\":[]}]},{\"level\":2,\"title\":\"💻 软件\",\"slug\":\"💻-软件\",\"link\":\"#💻-软件\",\"children\":[{\"level\":3,\"title\":\"ToDesk\",\"slug\":\"todesk\",\"link\":\"#todesk\",\"children\":[]},{\"level\":3,\"title\":\"向日葵\",\"slug\":\"向日葵\",\"link\":\"#向日葵\",\"children\":[]},{\"level\":3,\"title\":\"TeamViewer\",\"slug\":\"teamviewer\",\"link\":\"#teamviewer\",\"children\":[]}]},{\"level\":2,\"title\":\"🕸️ 网站\",\"slug\":\"🕸️-网站\",\"link\":\"#🕸️-网站\",\"children\":[{\"level\":3,\"title\":\"在线工具\",\"slug\":\"在线工具\",\"link\":\"#在线工具\",\"children\":[]},{\"level\":3,\"title\":\"百度脑图\",\"slug\":\"百度脑图\",\"link\":\"#百度脑图\",\"children\":[]},{\"level\":3,\"title\":\"网易见外\",\"slug\":\"网易见外\",\"link\":\"#网易见外\",\"children\":[]}]},{\"level\":2,\"title\":\"🔌 插件\",\"slug\":\"🔌-插件\",\"link\":\"#🔌-插件\",\"children\":[{\"level\":3,\"title\":\"屏幕录像机\",\"slug\":\"屏幕录像机\",\"link\":\"#屏幕录像机\",\"children\":[]},{\"level\":3,\"title\":\"Screenity\",\"slug\":\"screenity\",\"link\":\"#screenity\",\"children\":[]},{\"level\":3,\"title\":\"Vimeo Record\",\"slug\":\"vimeo-record\",\"link\":\"#vimeo-record\",\"children\":[]}]},{\"level\":2,\"title\":\"📖 资料\",\"slug\":\"📖-资料\",\"link\":\"#📖-资料\",\"children\":[{\"level\":3,\"title\":\"前端精读周刊\",\"slug\":\"前端精读周刊\",\"link\":\"#前端精读周刊\",\"children\":[]},{\"level\":3,\"title\":\"科技爱好者周刊\",\"slug\":\"科技爱好者周刊\",\"link\":\"#科技爱好者周刊\",\"children\":[]},{\"level\":3,\"title\":\"iOS 周报\",\"slug\":\"ios-周报\",\"link\":\"#ios-周报\",\"children\":[]}]},{\"level\":2,\"title\":\"✍️ 说明\",\"slug\":\"✍️-说明\",\"link\":\"#✍️-说明\",\"children\":[]},{\"level\":2,\"title\":\"🎬️ 广告\",\"slug\":\"🎬️-广告\",\"link\":\"#🎬️-广告\",\"children\":[]}],\"readingTime\":{\"minutes\":5.67,\"words\":1702},\"filePathRelative\":\"2023/0624-0630.md\",\"excerpt\":\"<h1> 好物周刊#11：远程桌面软件对对碰</h1>\\n<blockquote>\\n<p>不要哀求，学会争取。若是如此，终有所获。</p>\\n<p>原文：<a href=\\\"https://mp.weixin.qq.com/s/4az9STvM2jiwHhRa_k060Q\\\" target=\\\"_blank\\\" rel=\\\"noopener noreferrer\\\">https://mp.weixin.qq.com/s/4az9STvM2jiwHhRa_k060Q</a></p>\\n</blockquote>\\n<h2> 🎈 项目</h2>\\n<h3> <a href=\\\"https://github.com/fanmingming/live\\\" target=\\\"_blank\\\" rel=\\\"noopener noreferrer\\\">live</a></h3>\",\"copyright\":{\"author\":\"村雨遥\",\"license\":\"著作权归作者所有。商业转载请联系作者获得授权，非商业转载请注明出处\"},\"autoDesc\":true}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
