export const data = JSON.parse("{\"key\":\"v-4fc60d45\",\"path\":\"/2023/0729-0804.html\",\"title\":\"好物周刊#16：别致的二维码\",\"lang\":\"zh-CN\",\"frontmatter\":{\"description\":\"好物周刊#16：别致的二维码 不要哀求，学会争取。若是如此，终有所获。 原文：https://mp.weixin.qq.com/s/ERos0gfETiyjIpqNE_jBsA 🎈 项目 Hydro 链接\"},\"headers\":[{\"level\":2,\"title\":\"🎈 项目\",\"slug\":\"🎈-项目\",\"link\":\"#🎈-项目\",\"children\":[{\"level\":3,\"title\":\"Hydro\",\"slug\":\"hydro\",\"link\":\"#hydro\",\"children\":[]},{\"level\":3,\"title\":\"kkFileView\",\"slug\":\"kkfileview\",\"link\":\"#kkfileview\",\"children\":[]},{\"level\":3,\"title\":\"觅思文档\",\"slug\":\"觅思文档\",\"link\":\"#觅思文档\",\"children\":[]}]},{\"level\":2,\"title\":\"💻 软件\",\"slug\":\"💻-软件\",\"link\":\"#💻-软件\",\"children\":[{\"level\":3,\"title\":\"微信输入法\",\"slug\":\"微信输入法\",\"link\":\"#微信输入法\",\"children\":[]},{\"level\":3,\"title\":\"Lively Wallpaper\",\"slug\":\"lively-wallpaper\",\"link\":\"#lively-wallpaper\",\"children\":[]},{\"level\":3,\"title\":\"妙记多\",\"slug\":\"妙记多\",\"link\":\"#妙记多\",\"children\":[]}]},{\"level\":2,\"title\":\"🕸️ 网站\",\"slug\":\"🕸️-网站\",\"link\":\"#🕸️-网站\",\"children\":[{\"level\":3,\"title\":\"艺码\",\"slug\":\"艺码\",\"link\":\"#艺码\",\"children\":[]},{\"level\":3,\"title\":\"MewXAI 星月熊\",\"slug\":\"mewxai-星月熊\",\"link\":\"#mewxai-星月熊\",\"children\":[]},{\"level\":3,\"title\":\"Quick QR Art\",\"slug\":\"quick-qr-art\",\"link\":\"#quick-qr-art\",\"children\":[]}]},{\"level\":2,\"title\":\"🔌 插件\",\"slug\":\"🔌-插件\",\"link\":\"#🔌-插件\",\"children\":[{\"level\":3,\"title\":\"YouTube 双字幕\",\"slug\":\"youtube-双字幕\",\"link\":\"#youtube-双字幕\",\"children\":[]},{\"level\":3,\"title\":\"扩展管理器\",\"slug\":\"扩展管理器\",\"link\":\"#扩展管理器\",\"children\":[]},{\"level\":3,\"title\":\"Eagle for Chrome\",\"slug\":\"eagle-for-chrome\",\"link\":\"#eagle-for-chrome\",\"children\":[]}]},{\"level\":2,\"title\":\"📖 资料\",\"slug\":\"📖-资料\",\"link\":\"#📖-资料\",\"children\":[{\"level\":3,\"title\":\"程序员做饭指南\",\"slug\":\"程序员做饭指南\",\"link\":\"#程序员做饭指南\",\"children\":[]},{\"level\":3,\"title\":\"猴子都能懂的 Git 入门\",\"slug\":\"猴子都能懂的-git-入门\",\"link\":\"#猴子都能懂的-git-入门\",\"children\":[]},{\"level\":3,\"title\":\"TeachYourselfCS-CN\",\"slug\":\"teachyourselfcs-cn\",\"link\":\"#teachyourselfcs-cn\",\"children\":[]}]},{\"level\":2,\"title\":\"✍️ 说明\",\"slug\":\"✍️-说明\",\"link\":\"#✍️-说明\",\"children\":[]},{\"level\":2,\"title\":\"🎬️ 广告\",\"slug\":\"🎬️-广告\",\"link\":\"#🎬️-广告\",\"children\":[]}],\"readingTime\":{\"minutes\":8.23,\"words\":2468},\"filePathRelative\":\"2023/0729-0804.md\",\"excerpt\":\"<h1> 好物周刊#16：别致的二维码</h1>\\n<blockquote>\\n<p>不要哀求，学会争取。若是如此，终有所获。</p>\\n<p>原文：<a href=\\\"https://mp.weixin.qq.com/s/ERos0gfETiyjIpqNE_jBsA\\\" target=\\\"_blank\\\" rel=\\\"noopener noreferrer\\\">https://mp.weixin.qq.com/s/ERos0gfETiyjIpqNE_jBsA</a></p>\\n</blockquote>\\n<h2> 🎈 项目</h2>\\n<h3> Hydro</h3>\\n<ul>\\n<li><strong>链接</strong></li>\\n</ul>\",\"copyright\":{\"author\":\"村雨遥\",\"license\":\"著作权归作者所有。商业转载请联系作者获得授权，非商业转载请注明出处\"},\"autoDesc\":true}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
