export const data = JSON.parse("{\"key\":\"v-6a10d2da\",\"path\":\"/tutorial/dev-series/20230710-browser-plugin-install.html\",\"title\":\"如何在浏览器中安装插件\",\"lang\":\"zh-CN\",\"frontmatter\":{\"isOriginal\":true,\"category\":[\"开发工具\"],\"tag\":[\"浏览器\",\"Chrome\"],\"description\":\"如何在浏览器中安装插件 相关信息 不要哀求，学会争取。若是如此，终有所获。 提示 原文：https://mp.weixin.qq.com/s/KNiUsB_yMNjjmKXrcSjrXg\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://cunyu1943.github.io/tutorial/dev-series/20230710-browser-plugin-install.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"JavaPark\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"如何在浏览器中安装插件\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"如何在浏览器中安装插件 相关信息 不要哀求，学会争取。若是如此，终有所获。 提示 原文：https://mp.weixin.qq.com/s/KNiUsB_yMNjjmKXrcSjrXg\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"村雨遥\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"浏览器\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"Chrome\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"如何在浏览器中安装插件\\\",\\\"image\\\":[\\\"\\\"],\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"村雨遥\\\",\\\"url\\\":\\\"https://cunyu1943.github.io\\\",\\\"email\\\":\\\"747731461@qq.com\\\"}]}\"]]},\"headers\":[{\"level\":2,\"title\":\"一、前言\",\"slug\":\"一、前言\",\"link\":\"#一、前言\",\"children\":[]},{\"level\":2,\"title\":\"二、安装\",\"slug\":\"二、安装\",\"link\":\"#二、安装\",\"children\":[{\"level\":3,\"title\":\"1、在线安装\",\"slug\":\"_1、在线安装\",\"link\":\"#_1、在线安装\",\"children\":[]},{\"level\":3,\"title\":\"2、拖动安装\",\"slug\":\"_2、拖动安装\",\"link\":\"#_2、拖动安装\",\"children\":[]},{\"level\":3,\"title\":\"3、解压安装\",\"slug\":\"_3、解压安装\",\"link\":\"#_3、解压安装\",\"children\":[]}]},{\"level\":2,\"title\":\"三、总结\",\"slug\":\"三、总结\",\"link\":\"#三、总结\",\"children\":[]}],\"readingTime\":{\"minutes\":4.47,\"words\":1341},\"filePathRelative\":\"tutorial/dev-series/20230710-browser-plugin-install.md\",\"excerpt\":\"<h1> 如何在浏览器中安装插件</h1>\\n<div class=\\\"hint-container info\\\">\\n<p class=\\\"hint-container-title\\\">相关信息</p>\\n<p>不要哀求，学会争取。若是如此，终有所获。</p>\\n</div>\\n<div class=\\\"hint-container tip\\\">\\n<p class=\\\"hint-container-title\\\">提示</p>\\n<p>原文：<a href=\\\"https://mp.weixin.qq.com/s/KNiUsB_yMNjjmKXrcSjrXg\\\" target=\\\"_blank\\\" rel=\\\"noopener noreferrer\\\">https://mp.weixin.qq.com/s/KNiUsB_yMNjjmKXrcSjrXg</a></p>\\n</div>\",\"copyright\":{\"author\":\"村雨遥\",\"license\":\"著作权归作者所有。商业转载请联系作者获得授权，非商业转载请注明出处\"},\"autoDesc\":true}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
