export const data = JSON.parse("{\"key\":\"v-447a9870\",\"path\":\"/tutorial/efficiency-series/20220729-emoji.html\",\"title\":\"Emoji 表情大作战\",\"lang\":\"zh-CN\",\"frontmatter\":{\"isOriginal\":true,\"category\":[\"效率工具\"],\"tag\":[\"效率\",\"Emoji\"],\"description\":\"Emoji 表情大作战 共勉 不要哀求，学会争取。若是如此，终有所获。 原文 https://mp.weixin.qq.com/s/TZMiXLTsHqVl3VMp2Dcdlg\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://cunyu1943.github.io/tutorial/efficiency-series/20220729-emoji.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"JavaPark\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"Emoji 表情大作战\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"Emoji 表情大作战 共勉 不要哀求，学会争取。若是如此，终有所获。 原文 https://mp.weixin.qq.com/s/TZMiXLTsHqVl3VMp2Dcdlg\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"村雨遥\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"效率\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"Emoji\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"Emoji 表情大作战\\\",\\\"image\\\":[\\\"\\\"],\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"村雨遥\\\",\\\"url\\\":\\\"https://cunyu1943.github.io\\\",\\\"email\\\":\\\"747731461@qq.com\\\"}]}\"]]},\"headers\":[{\"level\":2,\"title\":\"前言\",\"slug\":\"前言\",\"link\":\"#前言\",\"children\":[]},{\"level\":2,\"title\":\"网站推荐\",\"slug\":\"网站推荐\",\"link\":\"#网站推荐\",\"children\":[{\"level\":3,\"title\":\"EmojiAll\",\"slug\":\"emojiall\",\"link\":\"#emojiall\",\"children\":[]},{\"level\":3,\"title\":\"Emojipedia\",\"slug\":\"emojipedia\",\"link\":\"#emojipedia\",\"children\":[]},{\"level\":3,\"title\":\"Get Emoji\",\"slug\":\"get-emoji\",\"link\":\"#get-emoji\",\"children\":[]},{\"level\":3,\"title\":\"Emoji Homepage\",\"slug\":\"emoji-homepage\",\"link\":\"#emoji-homepage\",\"children\":[]},{\"level\":3,\"title\":\"Emoji 列表\",\"slug\":\"emoji-列表\",\"link\":\"#emoji-列表\",\"children\":[]}]},{\"level\":2,\"title\":\"总结\",\"slug\":\"总结\",\"link\":\"#总结\",\"children\":[]}],\"readingTime\":{\"minutes\":3.1,\"words\":929},\"filePathRelative\":\"tutorial/efficiency-series/20220729-emoji.md\",\"excerpt\":\"<h1> Emoji 表情大作战</h1>\\n<div class=\\\"hint-container info\\\">\\n<p class=\\\"hint-container-title\\\">共勉</p>\\n<p>不要哀求，学会争取。若是如此，终有所获。</p>\\n</div>\\n<div class=\\\"hint-container tip\\\">\\n<p class=\\\"hint-container-title\\\">原文</p>\\n<p><a href=\\\"https://mp.weixin.qq.com/s/TZMiXLTsHqVl3VMp2Dcdlg\\\" target=\\\"_blank\\\" rel=\\\"noopener noreferrer\\\">https://mp.weixin.qq.com/s/TZMiXLTsHqVl3VMp2Dcdlg</a></p>\\n</div>\",\"copyright\":{\"author\":\"村雨遥\",\"license\":\"著作权归作者所有。商业转载请联系作者获得授权，非商业转载请注明出处\"},\"autoDesc\":true}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
