export const data = JSON.parse("{\"key\":\"v-613e4d8c\",\"path\":\"/weekly/2023/0916-0922.html\",\"title\":\"好物周刊#23：\",\"lang\":\"zh-CN\",\"frontmatter\":{\"index\":false,\"isOriginal\":true,\"category\":[\"好物周刊\"],\"tag\":[\"项目\",\"软件\",\"网站\",\"资料\",\"插件\"],\"description\":\"好物周刊#23： 共勉 不要哀求，学会争取。若是如此，终有所获。 原文 一、项目 二、软件 三、网站 视觉效果集合\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://cunyu1943.github.io/weekly/2023/0916-0922.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"JavaPark\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"好物周刊#23：\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"好物周刊#23： 共勉 不要哀求，学会争取。若是如此，终有所获。 原文 一、项目 二、软件 三、网站 视觉效果集合\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"村雨遥\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"项目\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"软件\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"网站\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"资料\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"插件\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"好物周刊#23：\\\",\\\"image\\\":[\\\"\\\"],\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"村雨遥\\\",\\\"url\\\":\\\"https://cunyu1943.github.io\\\",\\\"email\\\":\\\"747731461@qq.com\\\"}]}\"]]},\"headers\":[{\"level\":2,\"title\":\"一、项目\",\"slug\":\"一、项目\",\"link\":\"#一、项目\",\"children\":[]},{\"level\":2,\"title\":\"二、软件\",\"slug\":\"二、软件\",\"link\":\"#二、软件\",\"children\":[]},{\"level\":2,\"title\":\"三、网站\",\"slug\":\"三、网站\",\"link\":\"#三、网站\",\"children\":[{\"level\":3,\"title\":\"视觉效果集合\",\"slug\":\"视觉效果集合\",\"link\":\"#视觉效果集合\",\"children\":[]}]},{\"level\":2,\"title\":\"四、插件\",\"slug\":\"四、插件\",\"link\":\"#四、插件\",\"children\":[]},{\"level\":2,\"title\":\"五、资料\",\"slug\":\"五、资料\",\"link\":\"#五、资料\",\"children\":[]},{\"level\":2,\"title\":\"✍️ 说明\",\"slug\":\"✍️-说明\",\"link\":\"#✍️-说明\",\"children\":[]},{\"level\":2,\"title\":\"🎬️ 广告\",\"slug\":\"🎬️-广告\",\"link\":\"#🎬️-广告\",\"children\":[]}],\"readingTime\":{\"minutes\":1.16,\"words\":349},\"filePathRelative\":\"weekly/2023/0916-0922.md\",\"excerpt\":\"<h1> 好物周刊#23：</h1>\\n<div class=\\\"hint-container info\\\">\\n<p class=\\\"hint-container-title\\\">共勉</p>\\n<p>不要哀求，学会争取。若是如此，终有所获。</p>\\n</div>\\n<div class=\\\"hint-container tip\\\">\\n<p class=\\\"hint-container-title\\\">原文</p>\\n</div>\\n<h2> 一、项目</h2>\\n<h2> 二、软件</h2>\\n<h2> 三、网站</h2>\\n<h3> <a href=\\\"http://hepengwei.cn/#/html/visualDesign\\\" target=\\\"_blank\\\" rel=\\\"noopener noreferrer\\\">视觉效果集合</a></h3>\",\"copyright\":{\"author\":\"村雨遥\",\"license\":\"著作权归作者所有。商业转载请联系作者获得授权，非商业转载请注明出处\"},\"autoDesc\":true}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
