export const data = JSON.parse("{\"key\":\"v-60becfe6\",\"path\":\"/java-tutorial/javase-series/20220709-oop-1.html\",\"title\":\"面向对象的 3、5 知识点\",\"lang\":\"zh-CN\",\"frontmatter\":{\"isOriginal\":true,\"order\":1,\"category\":[\"Java 基础\"],\"tag\":[\"Java\"],\"description\":\"面向对象的 3、5 知识点 共勉 不要哀求，学会争取。若是如此，终有所获。 原文 https://mp.weixin.qq.com/s/Z4F7tsjLkPbTGy4_gJPQTw\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://cunyu1943.github.io/java-tutorial/javase-series/20220709-oop-1.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"JavaPark\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"面向对象的 3、5 知识点\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"面向对象的 3、5 知识点 共勉 不要哀求，学会争取。若是如此，终有所获。 原文 https://mp.weixin.qq.com/s/Z4F7tsjLkPbTGy4_gJPQTw\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"村雨遥\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"Java\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"面向对象的 3、5 知识点\\\",\\\"image\\\":[\\\"\\\"],\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"村雨遥\\\",\\\"url\\\":\\\"https://cunyu1943.github.io\\\",\\\"email\\\":\\\"747731461@qq.com\\\"}]}\"]]},\"headers\":[{\"level\":2,\"title\":\"前言\",\"slug\":\"前言\",\"link\":\"#前言\",\"children\":[]},{\"level\":2,\"title\":\"什么是面向对象？\",\"slug\":\"什么是面向对象\",\"link\":\"#什么是面向对象\",\"children\":[]},{\"level\":2,\"title\":\"面向对象的 5 大原则\",\"slug\":\"面向对象的-5-大原则\",\"link\":\"#面向对象的-5-大原则\",\"children\":[]},{\"level\":2,\"title\":\"面向对象的 3 大特性\",\"slug\":\"面向对象的-3-大特性\",\"link\":\"#面向对象的-3-大特性\",\"children\":[{\"level\":3,\"title\":\"封装\",\"slug\":\"封装\",\"link\":\"#封装\",\"children\":[]},{\"level\":3,\"title\":\"继承\",\"slug\":\"继承\",\"link\":\"#继承\",\"children\":[]},{\"level\":3,\"title\":\"多态\",\"slug\":\"多态\",\"link\":\"#多态\",\"children\":[]}]},{\"level\":2,\"title\":\"总结\",\"slug\":\"总结\",\"link\":\"#总结\",\"children\":[]}],\"readingTime\":{\"minutes\":6.51,\"words\":1954},\"filePathRelative\":\"java-tutorial/javase-series/20220709-oop-1.md\",\"excerpt\":\"<h1> 面向对象的 3、5 知识点</h1>\\n<div class=\\\"hint-container info\\\">\\n<p class=\\\"hint-container-title\\\">共勉</p>\\n<p>不要哀求，学会争取。若是如此，终有所获。</p>\\n</div>\\n<div class=\\\"hint-container tip\\\">\\n<p class=\\\"hint-container-title\\\">原文</p>\\n<p><a href=\\\"https://mp.weixin.qq.com/s/Z4F7tsjLkPbTGy4_gJPQTw\\\" target=\\\"_blank\\\" rel=\\\"noopener noreferrer\\\">https://mp.weixin.qq.com/s/Z4F7tsjLkPbTGy4_gJPQTw</a></p>\\n</div>\",\"copyright\":{\"author\":\"村雨遥\",\"license\":\"著作权归作者所有。商业转载请联系作者获得授权，非商业转载请注明出处\"},\"autoDesc\":true}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
