export const data = JSON.parse("{\"key\":\"v-7cb5c014\",\"path\":\"/QA/20230402-where-exercise-java-basics.html\",\"title\":\"想学好 Java 基础，应该去哪儿刷题\",\"lang\":\"zh-CN\",\"frontmatter\":{\"isOriginal\":true,\"category\":[\"你问我答\"],\"tag\":[\"Java\",\"刷题\"],\"description\":\"想学好 Java 基础，应该去哪儿刷题 共勉 不要哀求，学会争取。若是如此，终有所获。 前言 其实无论是哪门编程语言，只要把相关语法掌握之后，更重要的是一些算法、编程思想的提高。 既然已经对 Java 有了一定的了解了，那肯定基本语法没啥问题了，那在这里就提名几个常用的刷题网站，用来巩固 Java 基础的同时锻炼自己的编程思想，提高自己的编程能力！\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://cunyu1943.github.io/QA/20230402-where-exercise-java-basics.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"JavaPark\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"想学好 Java 基础，应该去哪儿刷题\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"想学好 Java 基础，应该去哪儿刷题 共勉 不要哀求，学会争取。若是如此，终有所获。 前言 其实无论是哪门编程语言，只要把相关语法掌握之后，更重要的是一些算法、编程思想的提高。 既然已经对 Java 有了一定的了解了，那肯定基本语法没啥问题了，那在这里就提名几个常用的刷题网站，用来巩固 Java 基础的同时锻炼自己的编程思想，提高自己的编程能力！\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"村雨遥\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"Java\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"刷题\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"想学好 Java 基础，应该去哪儿刷题\\\",\\\"image\\\":[\\\"\\\"],\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"村雨遥\\\",\\\"url\\\":\\\"https://cunyu1943.github.io\\\",\\\"email\\\":\\\"747731461@qq.com\\\"}]}\"]]},\"headers\":[{\"level\":2,\"title\":\"前言\",\"slug\":\"前言\",\"link\":\"#前言\",\"children\":[]},{\"level\":2,\"title\":\"网站推荐\",\"slug\":\"网站推荐\",\"link\":\"#网站推荐\",\"children\":[{\"level\":3,\"title\":\"牛客网\",\"slug\":\"牛客网\",\"link\":\"#牛客网\",\"children\":[]},{\"level\":3,\"title\":\"LeetCode\",\"slug\":\"leetcode\",\"link\":\"#leetcode\",\"children\":[]},{\"level\":3,\"title\":\"牛客网\",\"slug\":\"牛客网-1\",\"link\":\"#牛客网-1\",\"children\":[]},{\"level\":3,\"title\":\"赛码网\",\"slug\":\"赛码网\",\"link\":\"#赛码网\",\"children\":[]}]},{\"level\":2,\"title\":\"最后\",\"slug\":\"最后\",\"link\":\"#最后\",\"children\":[]}],\"readingTime\":{\"minutes\":3.88,\"words\":1164},\"filePathRelative\":\"QA/20230402-where-exercise-java-basics.md\",\"excerpt\":\"<h1> 想学好 Java 基础，应该去哪儿刷题</h1>\\n<div class=\\\"hint-container info\\\">\\n<p class=\\\"hint-container-title\\\">共勉</p>\\n<p>不要哀求，学会争取。若是如此，终有所获。</p>\\n</div>\\n<h2> 前言</h2>\\n<p>其实无论是哪门编程语言，只要把相关语法掌握之后，更重要的是一些算法、编程思想的提高。</p>\\n<p>既然已经对 <code>Java</code> 有了一定的了解了，那肯定基本语法没啥问题了，那在这里就提名几个常用的刷题网站，用来巩固 Java 基础的同时锻炼自己的编程思想，提高自己的编程能力！</p>\",\"copyright\":{\"author\":\"村雨遥\",\"license\":\"著作权归作者所有。商业转载请联系作者获得授权，非商业转载请注明出处\"},\"autoDesc\":true}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
