export const data = JSON.parse("{\"key\":\"v-3751854b\",\"path\":\"/java-tutorial/javase/20220705-binary-convert.html\",\"title\":\"常用进制转换\",\"lang\":\"zh-CN\",\"frontmatter\":{\"isOriginal\":true,\"order\":1,\"category\":[\"Java 基础\"],\"tag\":[\"Java\"],\"description\":\"常用进制转换 共勉 不要哀求，学会争取。若是如此，终有所获。 原文 https://mp.weixin.qq.com/s/2f_dODoVco-tSS66lF0U5A\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://cunyu1943.github.io/java-tutorial/javase/20220705-binary-convert.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"JavaPark\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"常用进制转换\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"常用进制转换 共勉 不要哀求，学会争取。若是如此，终有所获。 原文 https://mp.weixin.qq.com/s/2f_dODoVco-tSS66lF0U5A\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:image\",\"content\":\"https://cunyu1943.github.io/\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"name\":\"twitter:card\",\"content\":\"summary_large_image\"}],[\"meta\",{\"name\":\"twitter:image:alt\",\"content\":\"常用进制转换\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"村雨遥\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"Java\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"常用进制转换\\\",\\\"image\\\":[\\\"https://cunyu1943.github.io/\\\"],\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"村雨遥\\\",\\\"url\\\":\\\"https://cunyu1943.github.io\\\",\\\"email\\\":\\\"747731461@qq.com\\\"}]}\"]]},\"headers\":[{\"level\":2,\"title\":\"前言\",\"slug\":\"前言\",\"link\":\"#前言\",\"children\":[]},{\"level\":2,\"title\":\"二进制\",\"slug\":\"二进制\",\"link\":\"#二进制\",\"children\":[]},{\"level\":2,\"title\":\"十进制\",\"slug\":\"十进制\",\"link\":\"#十进制\",\"children\":[]},{\"level\":2,\"title\":\"八进制\",\"slug\":\"八进制\",\"link\":\"#八进制\",\"children\":[]},{\"level\":2,\"title\":\"十六进制\",\"slug\":\"十六进制\",\"link\":\"#十六进制\",\"children\":[]},{\"level\":2,\"title\":\"常用进制转换\",\"slug\":\"常用进制转换-1\",\"link\":\"#常用进制转换-1\",\"children\":[]},{\"level\":2,\"title\":\"总结\",\"slug\":\"总结\",\"link\":\"#总结\",\"children\":[]}],\"readingTime\":{\"minutes\":4.2,\"words\":1261},\"filePathRelative\":\"java-tutorial/javase/20220705-binary-convert.md\",\"excerpt\":\"<h1> 常用进制转换</h1>\\n<div class=\\\"hint-container info\\\">\\n<p class=\\\"hint-container-title\\\">共勉</p>\\n<p>不要哀求，学会争取。若是如此，终有所获。</p>\\n</div>\\n<div class=\\\"hint-container tip\\\">\\n<p class=\\\"hint-container-title\\\">原文</p>\\n<p><a href=\\\"https://mp.weixin.qq.com/s/2f_dODoVco-tSS66lF0U5A\\\" target=\\\"_blank\\\" rel=\\\"noopener noreferrer\\\">https://mp.weixin.qq.com/s/2f_dODoVco-tSS66lF0U5A</a></p>\\n</div>\",\"copyright\":{\"author\":\"村雨遥\",\"license\":\"著作权归作者所有。商业转载请联系作者获得授权，非商业转载请注明出处\"},\"autoDesc\":true}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
