export const data = JSON.parse("{\"key\":\"v-4d494f5e\",\"path\":\"/java-tutorial/javase/20220701-intro-to-java.html\",\"title\":\"Java 入门简介\",\"lang\":\"zh-CN\",\"frontmatter\":{\"isOriginal\":true,\"order\":1,\"category\":[\"Java 基础\"],\"tag\":\"Java\",\"description\":\"Java 入门简介 共勉 不要哀求，学会争取。若是如此，终有所获。 原文 https://mp.weixin.qq.com/s/aGz8CBOK5mW8xjAlstlMQw\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://cunyu1943.github.io/java-tutorial/javase/20220701-intro-to-java.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"JavaPark\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"Java 入门简介\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"Java 入门简介 共勉 不要哀求，学会争取。若是如此，终有所获。 原文 https://mp.weixin.qq.com/s/aGz8CBOK5mW8xjAlstlMQw\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:image\",\"content\":\"https://cunyu1943.github.io/\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"name\":\"twitter:card\",\"content\":\"summary_large_image\"}],[\"meta\",{\"name\":\"twitter:image:alt\",\"content\":\"Java 入门简介\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"村雨遥\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"Java\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"Java 入门简介\\\",\\\"image\\\":[\\\"https://cunyu1943.github.io/\\\"],\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"村雨遥\\\",\\\"url\\\":\\\"https://cunyu1943.github.io\\\",\\\"email\\\":\\\"747731461@qq.com\\\"}]}\"]]},\"headers\":[{\"level\":2,\"title\":\"1. 前言\",\"slug\":\"_1-前言\",\"link\":\"#_1-前言\",\"children\":[]},{\"level\":2,\"title\":\"2. 历史背景\",\"slug\":\"_2-历史背景\",\"link\":\"#_2-历史背景\",\"children\":[]},{\"level\":2,\"title\":\"3. 为什么使用 Java\",\"slug\":\"_3-为什么使用-java\",\"link\":\"#_3-为什么使用-java\",\"children\":[]},{\"level\":2,\"title\":\"4. Java 能做什么\",\"slug\":\"_4-java-能做什么\",\"link\":\"#_4-java-能做什么\",\"children\":[]},{\"level\":2,\"title\":\"5. Java 技术体系\",\"slug\":\"_5-java-技术体系\",\"link\":\"#_5-java-技术体系\",\"children\":[]},{\"level\":2,\"title\":\"6. 总结\",\"slug\":\"_6-总结\",\"link\":\"#_6-总结\",\"children\":[]}],\"readingTime\":{\"minutes\":5.4,\"words\":1620},\"filePathRelative\":\"java-tutorial/javase/20220701-intro-to-java.md\",\"excerpt\":\"<h1> Java 入门简介</h1>\\n<div class=\\\"hint-container info\\\">\\n<p class=\\\"hint-container-title\\\">共勉</p>\\n<p>不要哀求，学会争取。若是如此，终有所获。</p>\\n</div>\\n<div class=\\\"hint-container tip\\\">\\n<p class=\\\"hint-container-title\\\">原文</p>\\n<p><a href=\\\"https://mp.weixin.qq.com/s/aGz8CBOK5mW8xjAlstlMQw\\\" target=\\\"_blank\\\" rel=\\\"noopener noreferrer\\\">https://mp.weixin.qq.com/s/aGz8CBOK5mW8xjAlstlMQw</a></p>\\n</div>\",\"copyright\":{\"author\":\"村雨遥\",\"license\":\"著作权归作者所有。商业转载请联系作者获得授权，非商业转载请注明出处\"},\"autoDesc\":true}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
