export const data = JSON.parse("{\"key\":\"v-99b3fa96\",\"path\":\"/weekly/\",\"title\":\"创刊寄语\",\"lang\":\"zh-CN\",\"frontmatter\":{\"icon\":\"fa-solid fa-lightbulb\",\"index\":false,\"isOriginal\":true,\"description\":\"创刊寄语 共勉 不要哀求，学会争取。若是如此，终有所获。 一、前言 村雨遥的好物周刊，记录每周看到的有价值的信息，主要针对计算机领域，每周五发布。专栏目的在于记录让自己有印象的信息做一个备份及分享，阅读渠道如下： 博客 | 博客(国内) JavaPark 公众号：移动端推荐\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://cunyu1943.github.io/weekly/\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"JavaPark\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"创刊寄语\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"创刊寄语 共勉 不要哀求，学会争取。若是如此，终有所获。 一、前言 村雨遥的好物周刊，记录每周看到的有价值的信息，主要针对计算机领域，每周五发布。专栏目的在于记录让自己有印象的信息做一个备份及分享，阅读渠道如下： 博客 | 博客(国内) JavaPark 公众号：移动端推荐\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"村雨遥\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"创刊寄语\\\",\\\"image\\\":[\\\"\\\"],\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"村雨遥\\\",\\\"url\\\":\\\"https://cunyu1943.github.io\\\",\\\"email\\\":\\\"747731461@qq.com\\\"}]}\"]]},\"headers\":[{\"level\":2,\"title\":\"一、前言\",\"slug\":\"一、前言\",\"link\":\"#一、前言\",\"children\":[]},{\"level\":2,\"title\":\"二、介绍\",\"slug\":\"二、介绍\",\"link\":\"#二、介绍\",\"children\":[]},{\"level\":2,\"title\":\"三、交流\",\"slug\":\"三、交流\",\"link\":\"#三、交流\",\"children\":[]},{\"level\":2,\"title\":\"四、赞助\",\"slug\":\"四、赞助\",\"link\":\"#四、赞助\",\"children\":[]},{\"level\":2,\"title\":\"五、贡献\",\"slug\":\"五、贡献\",\"link\":\"#五、贡献\",\"children\":[]}],\"readingTime\":{\"minutes\":2.11,\"words\":634},\"filePathRelative\":\"weekly/README.md\",\"excerpt\":\"<h1> 创刊寄语</h1>\\n<div class=\\\"hint-container info\\\">\\n<p class=\\\"hint-container-title\\\">共勉</p>\\n<p>不要哀求，学会争取。若是如此，终有所获。</p>\\n</div>\\n<h2> 一、前言</h2>\\n<p>村雨遥的好物周刊，记录每周看到的有价值的信息，主要针对计算机领域，每周五发布。专栏目的在于记录让自己有印象的信息做一个备份及分享，阅读渠道如下：</p>\\n<ul>\\n<li><a href=\\\"https://cunyu1943.github.io/weekly\\\" target=\\\"_blank\\\" rel=\\\"noopener noreferrer\\\">博客</a> | <a href=\\\"https://cunyu1943.gitee.io/\\\" target=\\\"_blank\\\" rel=\\\"noopener noreferrer\\\">博客(国内)</a></li>\\n<li><a href=\\\"https://github.com/cunyu1943/JavaPark\\\" target=\\\"_blank\\\" rel=\\\"noopener noreferrer\\\">JavaPark</a></li>\\n<li><a href=\\\"https://mp.weixin.qq.com/mp/appmsgalbum?__biz=MzIyNTg2MjkzNw==&amp;action=getalbum&amp;album_id=2501145320567963650&amp;scene=173&amp;from_msgid=2247497779&amp;from_itemidx=1&amp;count=3&amp;nolastread=1#wechat_redirect\\\" target=\\\"_blank\\\" rel=\\\"noopener noreferrer\\\">公众号</a>：移动端推荐</li>\\n</ul>\",\"copyright\":{\"author\":\"村雨遥\",\"license\":\"著作权归作者所有。商业转载请联系作者获得授权，非商业转载请注明出处\"},\"autoDesc\":true}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
